services:
  web:
    build: ../
    volumes:
      - ../:/var/www/html
    ports:
      - 8080:80
    environment:
      - NAME=server1
    depends_on:
      - database
    networks:
      - bw-services

  database:
    image: mariadb:10.10
    environment:
      MYSQL_ROOT_PASSWORD: "itisveryhard"
      MYSQL_DATABASE: posty
      MYSQL_USER: posty
      MYSQL_PASSWORD: "123456"
    networks:
      - bw-services

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - bw-services
      - bw-docker

  bunkerweb:
    image: bunkerity/bunkerweb:1.5.10
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - MULTISITE=yes
      - SERVER_NAME=www.itis-waf.lan admin.itis-waf.lan
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - www.itis-waf.lan_REVERSE_PROXY_HOST=http://web
      - www.itis-waf.lan_REVERSE_PROXY_URL=/
      - admin.itis-waf.lan_REVERSE_PROXY_HOST=http://bw-ui:7000
      - admin.itis-waf.lan_REVERSE_PROXY_URL=/
      - admin.itis-waf.lan_USE_UI=yes
      - API_WHITELIST_IP=0.0.0.0/0
      - WHITELIST_URI=admin.itis-waf.lan
      - GENERATE_SELF_SIGNED_SSL=yes
    networks:
      - bw-universe
      - bw-services
      

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.10
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:bunkerweb@bw-db:3306/db 
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker
  
  bw-ui:
    image: bunkerity/bunkerweb-ui:1.5.10
    depends_on:
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:bunkerweb@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Itis$555 
    networks:
      - bw-universe
      - bw-docker

  bw-db:
    image: mariadb:10.10
    environment:
      - MYSQL_ROOT_PASSWORD="itisveryhard"
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=bunkerweb # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
