name: posty
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456$
      MYSQL_DATABASE: posty
      MYSQL_USER: posty
      MYSQL_PASSWORD: "123456"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
  web:
    build: ./
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80

    
